name: Org Terraform Format Checker

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
    TerraformFormatCheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2.0.2
              with:
                terraform_wrapper: false

            - name: Check formatting
              run: | 
                echo "Checking terraform configuration formatting..."
                if [[ $(terraform fmt --recursive | wc -l | xargs) == 0 ]]; then
                    echo "The terraform configuration is formatted correctly. You can proceed."
                else
                    echo "::error::The terraform configuration is not formatted correctly. Run the following locally and commit the changes before proceeding:"
                    echo "terraform fmt --recursive"
                    exit 1
                fi
